### ISSUE TITLE
Замечания по тестовому заданию 

### ISSUE THREAD

**Issue by mary-grigoriiva** [Ivansergee/vk-test#1]
Добрый вечер, Иван

Замечания по вашему тестовому заданию: во вкладке "Друзья" при нажатии на кнопку "Показать ещё" остальной список друзей не открывается (не отрабатывает совсем) или отображается не до конца (срабатывает пару раз, есть ещё друзья, а их уже не показывает)

**Comment by Ivansergee** [comment]
Проблема была в том, что счетчик отображенных элементов на вкладке "Друзья" не сбрасывался при повторном построении списка. Исправлено.

**Comment by mary-grigoriiva** [comment]
@Ivansergee Отлично) И второе небольшое замечание, пункт "цвет панели пользователя тем ярче, чем у большего числа пользователей из списка Исходный он находится в друзьях" здесь должен быть градиент. Например, на выборке из трех друзей: если человек есть у двух - он должен подсвечиваться, а сейчас ярко зеленым отмечается только тот друг, что у трех.

**Comment by Ivansergee** [comment]
@mary-grigoriiva ну у меня было сделано 5 вариантов цветов, которые применялись в зависимости от процента совпадающих друзей, но наверное почти всегда срабатывал первый вариант. Изменил логику работы, сейчас просто этот процент влияет на яркость фона карточки (если совпадений больше 1).
